exp_internal 1
set timeout 1

# Setup completion and fake command
send "source ../resources/picocompletion-demo_completion.fish\r"
expect -re "(.+>)"

send "function picocompletion-demo; echo 'do'; end\r"
expect -re "(.+>)"

set cmd "picocompletion-demo "
set test "Tab should show sub1 and sub2 for '${cmd}'"
# for some reason, bash completion doesn't show sub1-alias and sub2-alias
set candidates "sub1.*sub1-alias.*sub2.*sub2-alias.*"
run_completion_test $cmd $test $candidates

# now we show files in this test
# set cmd "picocompletion-demo sub1 "
# set test "Tab should not show completions for '${cmd}'"

set cmd "picocompletion-demo sub1 -"
set test "Tab should show sub1 options for '${cmd}'"
set candidates "--candidates.*--candidates=.*--num.*--str.*"
run_completion_test $cmd $test $candidates
