package picocli;

import org.junit.Before;
import org.junit.Test;
import picocli.CommandLine.TypeConversionException;
import picocli.CommandLine.ParameterException;

import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.Assert.*;

/**
 * Issue 1804 — Pluggable enum converters
 *
 * <p>Tests for the new IEnumConverter and CommandLine::registerEnumConverter(IEnumConverter)
 * functionality implemented in PR 2449. Verifies:<p>
 * <ul>
 *   <li>Registering a custom enum converter is used for options and positional parameters.</li>
 *   <li>An explicit ITypeConverter registered for an enum type takes precedence over the IEnumConverter.</li>
 *   <li>An IEnumConverter can fall back to the default enum conversion logic.</li>
 *   <li>The case-insensitive flag set via CommandLine::setCaseInsensitiveEnumValuesAllowed is passed to the IEnumConverter.</li>
 *   <li>Throwing a TypeConversionException from IEnumConverter results in a ParameterException from parseArgs with a friendly message.</li>
 *   <li>Registering a null IEnumConverter is rejected with NullPointerException.</li>
 *   <li>registerEnumConverter registers the converter for a command and its subcommands.</li>
 * </ul>
 * <p>Note that these tests were originally generated by an LLM instructed to reflect the existing style
 * of tests in the picocli codebase, and only slightly tweaked before including in the PR.</p>
 */
public class Issue1804PluggableEnumConverterTest {
    enum Color { RED, GREEN, BLUE }

    static class Opts {
        @CommandLine.Option(names = "--color") Color color;
        @CommandLine.Parameters(index = "0", arity = "0..1") Color pos;
    }

    private CommandLine cmd;
    private Opts opts;

    @Before
    public void setup() {
        opts = new Opts();
        cmd = new CommandLine(opts);
    }

    /**
     * Registering a custom enum type converter will result in that enum type converter being
     * used for options and positional parameters with that enum type.
     */
    @Test
    public void registeredEnumConverterIsUsedForOptionsAndPositionals() {
        final AtomicReference<String> seen = new AtomicReference<String>();
        cmd.registerEnumConverter(new CommandLine.IEnumConverter() {
            @Override
            public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                seen.set(value + ":" + caseInsensitiveEnumValuesAllowed);
                // return a constant of the expected enum type
                return enumType.cast(Color.BLUE);
            }
        });

        cmd.parseArgs("--color", "RED");
        assertEquals(Color.BLUE, opts.color);
        assertEquals("RED:false", seen.get());

        seen.set(null);
        cmd.parseArgs("GREEN");
        assertEquals(Color.BLUE, opts.pos);
        assertEquals("GREEN:false", seen.get());
    }

    /**
     * The custom enum type converter will NOT be used if a custom ITypeConverter is registered
     * for that enum type.
     */
    @Test
    public void explicitITypeConverterTakesPrecedenceOverEnumConverter() {
        final AtomicBoolean enumCalled = new AtomicBoolean(false);
        final AtomicBoolean typeCalled = new AtomicBoolean(false);

        cmd.registerEnumConverter(new CommandLine.IEnumConverter() {
            @Override
            public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                enumCalled.set(true);
                return enumType.cast(Color.RED);
            }
        });

        cmd.registerConverter(Color.class, new CommandLine.ITypeConverter<Color>() {
            @Override
            public Color convert(String value) throws Exception {
                typeCalled.set(true);
                return Color.GREEN;
            }
        });

        cmd.parseArgs("--color", "anything");
        assertTrue(typeCalled.get());
        assertFalse(enumCalled.get());
    }

    /**
     * A custom enum type converter falling back to the default enum type converter.
     */
    @Test
    public void enumConverterCanFallbackToDefault() {
        final AtomicReference<Boolean> usedDefault = new AtomicReference<Boolean>(Boolean.FALSE);

        cmd.registerEnumConverter(new CommandLine.IEnumConverter() {
            @Override
            public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                // This converter only specially handles the literal "SPECIAL"; otherwise delegate
                // to the library's DEFAULT_ENUM_CONVERTER to preserve standard behavior.
                if ("SPECIAL".equals(value) && enumType == Color.class) {
                    return enumType.cast(Color.BLUE);
                }
                @SuppressWarnings("unchecked")
                E result = (E) CommandLine.DEFAULT_ENUM_CONVERTER.convert(value, enumType, caseInsensitiveEnumValuesAllowed);
                if (enumType == Color.class && result instanceof Color) {
                    usedDefault.set(Boolean.TRUE);
                }
                return result;
            }
        });

        // Parsing a standard enum name uses the default converter via delegation.
        cmd.parseArgs("--color", "GREEN");
        assertTrue(usedDefault.get().booleanValue());
        assertEquals(Color.GREEN, opts.color);

        // Parsing the special value handled by custom converter.
        usedDefault.set(Boolean.FALSE);
        cmd.parseArgs("--color", "SPECIAL");
        assertEquals(Color.BLUE, opts.color);
        assertFalse(usedDefault.get().booleanValue());
    }

    /**
     * Setting CommandLine::setCaseInsensitiveEnumValuesAllowed(true) prior to parsing will
     * result in the custom enum type converter being called with value true.
     */
    @Test
    public void caseInsensitiveFlagTrueIsPassedToEnumConverter() {
        final AtomicReference<Boolean> received = new AtomicReference<Boolean>();
        cmd.registerEnumConverter(new CommandLine.IEnumConverter() {
            @Override
            public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                received.set(caseInsensitiveEnumValuesAllowed);
                return enumType.cast(Color.RED);
            }
        });

        cmd.setCaseInsensitiveEnumValuesAllowed(true);
        cmd.parseArgs("--color", "whatever");
        assertTrue(received.get().booleanValue());
    }

    /**
     * Not calling CommandLine::setCaseInsensitiveEnumValuesAllowed prior to parsing will
     * result in the custom enum type converter being called with value false.
     */
    @Test
    public void caseInsensitiveFlagDefaultIsFalsePassedToEnumConverter() {
        final AtomicReference<Boolean> received = new AtomicReference<Boolean>();
        cmd.registerEnumConverter(new CommandLine.IEnumConverter() {
            @Override
            public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                received.set(caseInsensitiveEnumValuesAllowed);
                return enumType.cast(Color.RED);
            }
        });

        // do not call setCaseInsensitiveEnumValuesAllowed(true)
        cmd.parseArgs("--color", "whatever");
        assertFalse(received.get().booleanValue());
    }

    /**
     * Throwing a TypeConversionException from the registered custom enum type converter will
     * result in a ParameterException with a user-friendly message from CommandLine::parseArgs.
     */
    @Test
    public void throwingTypeConversionExceptionFromEnumConverterYieldsParameterException() {
        cmd.registerEnumConverter(new CommandLine.IEnumConverter() {
            @Override
            public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                throw new TypeConversionException("custom converter failure for: " + value);
            }
        });

        try {
            cmd.parseArgs("--color", "X");
            fail("Expected ParameterException");
        } catch (ParameterException ex) {
            String msg = ex.getMessage();
            // full message is currently "Invalid value for option '--color': custom converter failure for: X"
            assertTrue(msg.contains("custom converter failure"));
        }
    }

    /**
     * Registering a null custom enum type converter is rejected immediately with a NullPointerException.
     */
    @Test(expected = NullPointerException.class)
    public void registeringNullEnumConverterIsRejected() {
        cmd.registerEnumConverter(null);
    }

    /**
     * Calling CommandLine::registerEnumConverter will register the custom enum type converter
     * for that command and all its subcommands and sub-subcommands.
     */
    @Test
    public void registerEnumConverterRegistersForCommandAndSubcommands() {
        // Use explicit @Command-annotated root to avoid InitializationException from new Object()
        @CommandLine.Command(name = "root")
        class RootCmd { }

        CommandLine root = new CommandLine(new RootCmd());

        final Opts subOpts = new Opts();
        CommandLine sub = new CommandLine(subOpts);
        root.addSubcommand("sub", sub);

        final Opts subsubOpts = new Opts();
        CommandLine subsub = new CommandLine(subsubOpts);
        sub.addSubcommand("subsub", subsub);

        // Register enum converter on root that returns different constants based on a prefix
        root.registerEnumConverter(new CommandLine.IEnumConverter() {
            @Override
            public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                // Distinguish by value prefix to indicate which command provided the value.
                if (value.startsWith("root:")) return enumType.cast(Color.RED);
                if (value.startsWith("sub:")) return enumType.cast(Color.GREEN);
                if (value.startsWith("subsub:")) return enumType.cast(Color.BLUE);
                // fallback to default
                @SuppressWarnings("unchecked")
                E result = (E) CommandLine.DEFAULT_ENUM_CONVERTER.convert(value, enumType, caseInsensitiveEnumValuesAllowed);
                return result;
            }
        });

        // Parse using subcommand via root: should use converter registered on root
        root.parseArgs("sub", "--color", "sub:anything");
        assertEquals(Color.GREEN, subOpts.color);

        // Parse directly on sub: should inherit converter from root registration
        sub.parseArgs("--color", "sub:direct");
        assertEquals(Color.GREEN, subOpts.color);

        // Parse on subsub via root:sub subcommand invocation
        root.parseArgs("sub", "subsub", "--color", "subsub:via-root");
        assertEquals(Color.BLUE, subsubOpts.color);

        // Parse directly on subsub: should inherit converter as well
        subsub.parseArgs("--color", "subsub:direct");
        assertEquals(Color.BLUE, subsubOpts.color);

        // Also verify root registration still allows parsing a default enum name via fallback
        root.parseArgs("sub", "--color", "GREEN"); // should be processed by DEFAULT_ENUM_CONVERTER
        assertEquals(Color.GREEN, subOpts.color);

        // Ensure re-registering on root/sub/subsub does not throw
        try {
            root.registerEnumConverter(new CommandLine.IEnumConverter() {
                @Override
                public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                    return enumType.cast(Color.GREEN);
                }
            });
            sub.registerEnumConverter(new CommandLine.IEnumConverter() {
                @Override
                public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                    return enumType.cast(Color.GREEN);
                }
            });
            subsub.registerEnumConverter(new CommandLine.IEnumConverter() {
                @Override
                public <E extends Enum<E>> E convert(String value, Class<E> enumType, boolean caseInsensitiveEnumValuesAllowed) throws Exception {
                    return enumType.cast(Color.GREEN);
                }
            });
        } catch (Exception ex) {
            fail("Unexpected exception when re-registering converters: " + ex);
        }
    }
}
